id: PD70799DF
initial_creation_type: input
source_metadata:
  Title: समन्तभद्र नाम साधन टीका
  Editor: Kimiaki Tanaka
  Publisher: Watanabe Publishing
  Place of Publication: Tokyo
  Year: '2017'
  समन्तभद्र नाम साधन टीका:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:06:45.092605'
last_modified_at: '2022-03-08T17:06:45.092615'
